server:
  port: 8082
spring:
  messages:
    basename: i18n.login
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/bookrate?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: Sa123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.wudi.model
  mapper-locations: classpath:mapping/*.xml